//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1185915 {
            get {
                object obj = ResourceManager.GetObject("1185915", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2022010100000273499 {
            get {
                object obj = ResourceManager.GetObject("2022010100000273499", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _23867240 {
            get {
                object obj = ResourceManager.GetObject("23867240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _66318217_database_icon_or_logo_in_modern_line_style_high_quality_black_outline_pictogram_for_web_site_design {
            get {
                object obj = ResourceManager.GetObject("66318217-database-icon-or-logo-in-modern-line-style-high-quality-black-outline-pi" +
                        "ctogram-for-web-site-design", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7fe06fd33791f89217ef8cb12268f7a1 {
            get {
                object obj = ResourceManager.GetObject("7fe06fd33791f89217ef8cb12268f7a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _86403_press_lg {
            get {
                object obj = ResourceManager.GetObject("86403_press_lg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b0e1e2c3_a614_4392_967d_5b92bce04779 {
            get {
                object obj = ResourceManager.GetObject("b0e1e2c3-a614-4392-967d-5b92bce04779", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b0e1e2c3_a614_4392_967d_5b92bce047791 {
            get {
                object obj = ResourceManager.GetObject("b0e1e2c3-a614-4392-967d-5b92bce047791", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap citadel_life_safety_K4dBR3TiH4U_unsplash {
            get {
                object obj = ResourceManager.GetObject("citadel-life-safety-K4dBR3TiH4U-unsplash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database_icon_logo_modern_line_style_high_quality_black_outline_pictogram_web_site_design_mobile_apps_vector_81367946 {
            get {
                object obj = ResourceManager.GetObject("database-icon-logo-modern-line-style-high-quality-black-outline-pictogram-web-sit" +
                        "e-design-mobile-apps-vector-81367946", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database_icon_logo_modern_line_style_high_quality_black_outline_pictogram_web_site_design_mobile_apps_vector_813679461 {
            get {
                object obj = ResourceManager.GetObject("database-icon-logo-modern-line-style-high-quality-black-outline-pictogram-web-sit" +
                        "e-design-mobile-apps-vector-813679461", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database_icon_logo_modern_line_style_high_quality_black_outline_pictogram_web_site_design_mobile_apps_vector_813679462 {
            get {
                object obj = ResourceManager.GetObject("database-icon-logo-modern-line-style-high-quality-black-outline-pictogram-web-sit" +
                        "e-design-mobile-apps-vector-813679462", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database_icon_logo_modern_line_style_high_quality_black_outline_pictogram_web_site_design_mobile_apps_vector_8136794621 {
            get {
                object obj = ResourceManager.GetObject("database-icon-logo-modern-line-style-high-quality-black-outline-pictogram-web-sit" +
                        "e-design-mobile-apps-vector-8136794621", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gettyimages_1439344468_612x612 {
            get {
                object obj = ResourceManager.GetObject("gettyimages-1439344468-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gettyimages_1439344468_612x6121 {
            get {
                object obj = ResourceManager.GetObject("gettyimages-1439344468-612x6121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap giant_185883 {
            get {
                object obj = ResourceManager.GetObject("giant_185883", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gillette_Sensor {
            get {
                object obj = ResourceManager.GetObject("Gillette_Sensor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hand_holding_spanner_symbol_repairs_maintenance_service_concept_2C9EC6M {
            get {
                object obj = ResourceManager.GetObject("hand-holding-spanner-symbol-repairs-maintenance-service-concept-2C9EC6M", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__1_ {
            get {
                object obj = ResourceManager.GetObject("images (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__2_ {
            get {
                object obj = ResourceManager.GetObject("images (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap isawred_P9YUxV6_YUc_unsplash {
            get {
                object obj = ResourceManager.GetObject("isawred-P9YUxV6_YUc-unsplash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap isawred_P9YUxV6_YUc_unsplash1 {
            get {
                object obj = ResourceManager.GetObject("isawred-P9YUxV6_YUc-unsplash1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap isawred_P9YUxV6_YUc_unsplash2 {
            get {
                object obj = ResourceManager.GetObject("isawred-P9YUxV6_YUc-unsplash2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap isawred_P9YUxV6_YUc_unsplash3 {
            get {
                object obj = ResourceManager.GetObject("isawred-P9YUxV6_YUc-unsplash3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap isawred_P9YUxV6_YUc_unsplash4 {
            get {
                object obj = ResourceManager.GetObject("isawred-P9YUxV6_YUc-unsplash4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap isawred_P9YUxV6_YUc_unsplash5 {
            get {
                object obj = ResourceManager.GetObject("isawred-P9YUxV6_YUc-unsplash5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap isawred_P9YUxV6_YUc_unsplash6 {
            get {
                object obj = ResourceManager.GetObject("isawred-P9YUxV6_YUc-unsplash6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1313665882_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1313665882-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_639849256_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-639849256-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap large_nsk_286_s {
            get {
                object obj = ResourceManager.GetObject("large-nsk-286-s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maintenance_line_icon_free_vector {
            get {
                object obj = ResourceManager.GetObject("maintenance-line-icon-free-vector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maintenance_record {
            get {
                object obj = ResourceManager.GetObject("maintenance-record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap max471_voltage_current_sensor_module_datasheet {
            get {
                object obj = ResourceManager.GetObject("max471-voltage-current-sensor-module-datasheet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_analyticsprocessingdashboarddatastats_glyph_icon_on_tran_png_image_1219585 {
            get {
                object obj = ResourceManager.GetObject("pngtree-analyticsprocessingdashboarddatastats-glyph-icon-on-tran-png-image_121958" +
                        "5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_beautiful_maintenance_vector_glyph_icon_png_image_1799017 {
            get {
                object obj = ResourceManager.GetObject("pngtree-beautiful-maintenance-vector-glyph-icon-png-image_1799017", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_black_maintenance_tool_icon_free_png_transparent_material_image_2290611 {
            get {
                object obj = ResourceManager.GetObject("pngtree-black-maintenance-tool-icon-free-png-transparent-material-image_2290611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_dashboard_glyph_black_icon_png_image_691533 {
            get {
                object obj = ResourceManager.GetObject("pngtree-dashboard-glyph-black-icon-png-image_691533", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_settings_maintenance_icon_on_white_background_png_image_4945796 {
            get {
                object obj = ResourceManager.GetObject("pngtree-settings-maintenance-icon-on-white-background-png-image_4945796", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Predictive_maintenance_1 {
            get {
                object obj = ResourceManager.GetObject("Predictive-maintenance-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Predictive_maintenance_11 {
            get {
                object obj = ResourceManager.GetObject("Predictive-maintenance-11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Predictive_maintenance_12 {
            get {
                object obj = ResourceManager.GetObject("Predictive-maintenance-12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Predictive_maintenance_13 {
            get {
                object obj = ResourceManager.GetObject("Predictive-maintenance-13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Predictive_maintenance_14 {
            get {
                object obj = ResourceManager.GetObject("Predictive-maintenance-14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap predictive_maintenance_and_IoT_main_photo_min {
            get {
                object obj = ResourceManager.GetObject("predictive-maintenance-and-IoT-main-photo-min", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap predictive_maintenance_and_IoT_main_photo_min1 {
            get {
                object obj = ResourceManager.GetObject("predictive-maintenance-and-IoT-main-photo-min1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap press1 {
            get {
                object obj = ResourceManager.GetObject("press1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vintage_gear_machinery_logo_by_yahyaanasatokillah {
            get {
                object obj = ResourceManager.GetObject("Vintage-gear-machinery-logo-by-yahyaanasatokillah", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vintage_gear_machinery_logo_by_yahyaanasatokillah1 {
            get {
                object obj = ResourceManager.GetObject("Vintage-gear-machinery-logo-by-yahyaanasatokillah1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap what_is_pressure_sensor {
            get {
                object obj = ResourceManager.GetObject("what-is-pressure-sensor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2025_08_31_at_01_04_43_aaa6e965 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2025-08-31 at 01.04.43_aaa6e965", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
